package com.duyanhan.forum.dao;

import com.duyanhan.forum.domain.BlackUser;
import com.duyanhan.forum.domain.BlackUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlackUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blackuser
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    long countByExample(BlackUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blackuser
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    int deleteByExample(BlackUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blackuser
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blackuser
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    int insert(BlackUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blackuser
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    int insertSelective(BlackUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blackuser
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    List<BlackUser> selectByExample(BlackUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blackuser
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    BlackUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blackuser
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") BlackUser record, @Param("example") BlackUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blackuser
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    int updateByExample(@Param("record") BlackUser record, @Param("example") BlackUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blackuser
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    int updateByPrimaryKeySelective(BlackUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blackuser
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    int updateByPrimaryKey(BlackUser record);
}