package com.duyanhan.forum.dao;

import com.duyanhan.forum.domain.Block;
import com.duyanhan.forum.domain.BlockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    long countByExample(BlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    int deleteByExample(BlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    int insert(Block record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    int insertSelective(Block record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    List<Block> selectByExample(BlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    Block selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") Block record, @Param("example") BlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    int updateByExample(@Param("record") Block record, @Param("example") BlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    int updateByPrimaryKeySelective(Block record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    int updateByPrimaryKey(Block record);
}