package com.duyanhan.forum.domain;

public class BlackUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blackuser.id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blackuser.userinfo_id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private Integer userinfoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blackuser.id
     *
     * @return the value of blackuser.id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blackuser.id
     *
     * @param id the value for blackuser.id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blackuser.userinfo_id
     *
     * @return the value of blackuser.userinfo_id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public Integer getUserinfoId() {
        return userinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blackuser.userinfo_id
     *
     * @param userinfoId the value for blackuser.userinfo_id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setUserinfoId(Integer userinfoId) {
        this.userinfoId = userinfoId;
    }
}