package com.duyanhan.forum.domain;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.postTime
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private Date posttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.updateTime
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.post_id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.userinfo_id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private Integer userinfoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.postTime
     *
     * @return the value of comment.postTime
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public Date getPosttime() {
        return posttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.postTime
     *
     * @param posttime the value for comment.postTime
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setPosttime(Date posttime) {
        this.posttime = posttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.updateTime
     *
     * @return the value of comment.updateTime
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.updateTime
     *
     * @param updatetime the value for comment.updateTime
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.post_id
     *
     * @return the value of comment.post_id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.post_id
     *
     * @param postId the value for comment.post_id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.userinfo_id
     *
     * @return the value of comment.userinfo_id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public Integer getUserinfoId() {
        return userinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.userinfo_id
     *
     * @param userinfoId the value for comment.userinfo_id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setUserinfoId(Integer userinfoId) {
        this.userinfoId = userinfoId;
    }
}