package com.duyanhan.forum.domain;

import java.util.Date;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.title
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.content
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.postTime
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private Date posttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.updateTime
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.block_id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private Integer blockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.userinfo_id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private Integer userinfoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id
     *
     * @return the value of post.id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id
     *
     * @param id the value for post.id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.title
     *
     * @return the value of post.title
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.title
     *
     * @param title the value for post.title
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.content
     *
     * @return the value of post.content
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.content
     *
     * @param content the value for post.content
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.postTime
     *
     * @return the value of post.postTime
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public Date getPosttime() {
        return posttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.postTime
     *
     * @param posttime the value for post.postTime
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setPosttime(Date posttime) {
        this.posttime = posttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.updateTime
     *
     * @return the value of post.updateTime
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.updateTime
     *
     * @param updatetime the value for post.updateTime
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.block_id
     *
     * @return the value of post.block_id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public Integer getBlockId() {
        return blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.block_id
     *
     * @param blockId the value for post.block_id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setBlockId(Integer blockId) {
        this.blockId = blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.userinfo_id
     *
     * @return the value of post.userinfo_id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public Integer getUserinfoId() {
        return userinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.userinfo_id
     *
     * @param userinfoId the value for post.userinfo_id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setUserinfoId(Integer userinfoId) {
        this.userinfoId = userinfoId;
    }
}