package com.duyanhan.forum.domain;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.username
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.password
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.sex
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.personalDescription
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    private String personaldescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.username
     *
     * @return the value of userinfo.username
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.username
     *
     * @param username the value for userinfo.username
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.password
     *
     * @return the value of userinfo.password
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.password
     *
     * @param password the value for userinfo.password
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.sex
     *
     * @return the value of userinfo.sex
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.sex
     *
     * @param sex the value for userinfo.sex
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.personalDescription
     *
     * @return the value of userinfo.personalDescription
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public String getPersonaldescription() {
        return personaldescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.personalDescription
     *
     * @param personaldescription the value for userinfo.personalDescription
     *
     * @mbg.generated Sat May 12 17:14:45 CST 2018
     */
    public void setPersonaldescription(String personaldescription) {
        this.personaldescription = personaldescription;
    }
}